# -*- coding: utf-8 -*-
"""claims — verification/claims.json 정본 → CLAIM-EVIDENCE-MAP.md 생성 + explain (Phase4).

claim 필수 필드: id·title·guarantee_class·boundary(정직 경계 한 문장)·evidence_steps.
실패 의미론: evidence step 실패 = 해당 claim invalidated (그 claim 만).
"""
import os
import json

from . import context as cx

CLAIMS_PATH = os.path.join(cx.ROOT, "verification", "claims.json")
MAP_PATH = os.path.join(cx.REPORTS, "CLAIM-EVIDENCE-MAP.md")


def load_claims():
    doc = json.load(open(CLAIMS_PATH, encoding="utf-8"))
    for c in doc["claims"]:
        for k in ("id", "title", "guarantee_class", "boundary", "evidence_steps"):
            if k not in c:
                raise ValueError(f"claim missing '{k}': {c.get('id', c)}")
    return doc["claims"]


def _latest_result():
    p = os.path.join(cx.REPORTS, "REPRODUCE-RESULT.json")
    if os.path.exists(p):
        return json.load(open(p, encoding="utf-8"))
    return None


def claim_status(claim, result):
    """최신 REPRODUCE-RESULT 기준 claim 상태 — 전 evidence step pass 여야 pass."""
    if not result:
        return "unknown"
    st = result.get("steps", {})
    vals = [st.get(sid, {}).get("pass") for sid in claim["evidence_steps"] if sid in st]
    if not vals:
        return "not-run"
    return "pass" if all(vals) else "FAIL"


def explain(claim_id):
    """단일 claim 설명 텍스트 (cli explain --claim)."""
    claims = {c["id"]: c for c in load_claims()}
    if claim_id not in claims:
        return f"unknown claim: {claim_id}\nknown: " + ", ".join(sorted(claims))
    c = claims[claim_id]
    res = _latest_result()
    lines = [f"claim: {c['id']}", f"  title    : {c['title']}",
             f"  class    : {c['guarantee_class']}", f"  boundary : {c['boundary']}",
             f"  evidence : {', '.join(c['evidence_steps'])}",
             f"  latest   : {claim_status(c, res)}"
             + (f" (bundle={res['bundle']}, mode={res.get('mode')})" if res else "")]
    for f_ in c.get("authoritative_files", []):
        lines.append(f"  authority: {f_}")
    return "\n".join(lines)


def check_claims():
    """claims.json 무결성 drift gate (QF-0711 U7a) — 필드 존재(load_claims) +
    evidence_steps 비어있지 않음 + 최신 REPRODUCE-RESULT 스텝에 실존(스텝 rename/삭제 시 포착).
    result 부재 시 구조만 검증. 반환: 문제 리스트(빈 리스트=all_ok)."""
    claims = load_claims()
    res = _latest_result()
    keys = set(res.get("steps", {})) if res else set()
    problems = []
    seen = set()
    for c in claims:
        if c["id"] in seen:
            problems.append(f"{c['id']}: duplicate id")
        seen.add(c["id"])
        if not c["evidence_steps"]:
            problems.append(f"{c['id']}: empty evidence_steps")
        if keys:
            miss = [s for s in c["evidence_steps"] if s not in keys]
            if miss:
                problems.append(f"{c['id']}: evidence_steps not in latest result {miss}")
    return problems


def write_claim_map():
    """reviewer-facing Markdown 생성 (docs/EVIDENCE-MAP.md 수동 v0 의 자동 후계)."""
    claims = load_claims()
    res = _latest_result()
    out = ["# Claim-Evidence Map (generated)",
           "",
           "> Generated by `python -m qf_verify write-claim-map` from `verification/claims.json`",
           "> against the latest `reports/REPRODUCE-RESULT.json`. Every claim carries its honest",
           "> boundary — a failing evidence step invalidates exactly that claim, nothing more.",
           ""]
    for c in claims:
        out.append(f"## {c['id']}")
        out.append("")
        out.append(f"**{c['title']}**  ")
        out.append(f"class: `{c['guarantee_class']}` · latest: **{claim_status(c, res)}**")
        out.append("")
        out.append(f"- Evidence steps: {', '.join('`' + s + '`' for s in c['evidence_steps'])}")
        for f_ in c.get("authoritative_files", []):
            out.append(f"- Authority: `{f_}`")
        out.append(f"- **Boundary**: {c['boundary']}")
        out.append("")
    os.makedirs(cx.REPORTS, exist_ok=True)
    open(MAP_PATH, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
    return MAP_PATH
