# -*- coding: utf-8 -*-
"""doc_counts — 공개 수치 단일출처 (QF-0711 U1 CountOntology).

REGISTRY-MANIFEST.json + SEMANTIC-GUARANTEES.json headline_split 에서 canonical count 를 파생해
  1. registry/COUNT-ONTOLOGY.json 생성(5-튜플 {entity,namespace,population,guarantee,count}+glossary)
  2. 서술문서의 <!-- BEGIN generated:counts --> 마커 블록을 채움(현재 README.md; ARCH/Spec 은 U5)
비파괴: root 비입력(registry_root = 봉인 id:u_hash 만) → 이 파일 변경은 root 불변.

사용:
  python -m qf_witness.registry.doc_counts            # 생성/치환(write)
  python -m qf_witness.registry.doc_counts --check    # 비변경 정합검사(all_ok) — witness batch·drift gate
"""
import json
import os
import re
import sys

from qf_witness.core.paths import ROOT

MANIFEST = os.path.join(ROOT, "registry", "REGISTRY-MANIFEST.json")
SEMANTIC = os.path.join(ROOT, "registry", "SEMANTIC-GUARANTEES.json")
ONTOLOGY = os.path.join(ROOT, "registry", "COUNT-ONTOLOGY.json")

MARK_BEGIN = "<!-- BEGIN generated:counts src=registry/COUNT-ONTOLOGY.json -->"
MARK_END = "<!-- END generated:counts -->"
DOC_TARGETS = ["README.md"]   # ARCH/Spec 은 U5(DocCurrentHistorySplit) 재작성 시 마커 추가


def _compute():
    m = json.load(open(MANIFEST, encoding="utf-8"))
    a = m["apps"]
    root = m["registry_root_hash"]
    app_cls = json.load(open(SEMANTIC, encoding="utf-8"))["headline_split"]["by_kind_class"]["app"]
    modules, unique = m["modules"]["count"], a["unique_app_count"]
    files, cached = a["total_files"], a["cached_app_side_module_count"]

    counts = [
        {"entity": "module", "namespace": "registry", "population": "all",
         "guarantee": "unitary_equiv", "count": modules, "source": "REGISTRY-MANIFEST.modules.count"},
        {"entity": "app", "namespace": "registry", "population": "unique",
         "guarantee": "all", "count": unique, "source": "REGISTRY-MANIFEST.apps.unique_app_count"},
        {"entity": "app", "namespace": "registry", "population": "file",
         "guarantee": "all", "count": files, "source": "REGISTRY-MANIFEST.apps.total_files"},
        {"entity": "app", "namespace": "registry", "population": "cached_leaf",
         "guarantee": "unitary_equiv", "count": cached,
         "source": "REGISTRY-MANIFEST.apps.cached_app_side_module_count"},
    ]
    for cls, n in sorted(app_cls.items()):
        counts.append({"entity": "app", "namespace": "semantic", "population": "file",
                       "guarantee": cls, "count": n,
                       "source": f"SEMANTIC-GUARANTEES.headline_split.by_kind_class.app.{cls}"})

    return {
        "_schema": "qf-count-ontology/v1",
        "_note": ("Single source for every public count. Generated by qf_witness.registry.doc_counts "
                  "from REGISTRY-MANIFEST.json + SEMANTIC-GUARANTEES.json headline_split. Do not hand-edit."),
        "generated_from_root": root,
        "glossary": {
            "module": "sealed base module (specs/modules/*.pg -> registry/modules/*.sealed.json)",
            "unique_app": "distinct application id (specs/apps/*.app.pg -> registry/apps/*.sealed.json)",
            "app_file": "every registry/apps/*.sealed.json = unique_apps + cached app-side module re-seals",
            "cached_app_side_module": ("module re-sealed under registry/apps as an app_assemble leaf "
                                       "artifact -- NOT a new unique app"),
            "app_entry": "one app-level semantic-guarantee entry per app_file",
        },
        "headline": {"modules": modules, "unique_apps": unique, "app_files": files,
                     "cached_leaf": cached, "app_by_guarantee": app_cls, "root16": root[:16]},
        "counts": counts,
    }


def _readme_block(o):
    h = o["headline"]
    return (f"{MARK_BEGIN}\n"
            f"- **{h['modules']} sealed modules · {h['unique_apps']} unique applications** · "
            f"registry root `{h['root16']}…`\n"
            f"  ({h['app_files']} app-file entries = {h['unique_apps']} unique + {h['cached_leaf']} "
            f"cached app-side re-seals;\n"
            f"  live source [`registry/REGISTRY-MANIFEST.json`](registry/REGISTRY-MANIFEST.json)).\n"
            f"{MARK_END}")


def _sub_markers(text, block):
    pat = re.compile(re.escape(MARK_BEGIN) + r".*?" + re.escape(MARK_END), re.S)
    return pat.sub(lambda _: block, text) if pat.search(text) else None


def run(check):
    o = _compute()
    ont_new = json.dumps(o, ensure_ascii=False, indent=2) + "\n"
    block = _readme_block(o)
    ok, stale = True, []

    cur = open(ONTOLOGY, encoding="utf-8").read() if os.path.exists(ONTOLOGY) else None
    if cur != ont_new:
        ok = False
        stale.append("COUNT-ONTOLOGY.json")
        if not check:
            open(ONTOLOGY, "w", encoding="utf-8", newline="\n").write(ont_new)

    for rel in DOC_TARGETS:
        p = os.path.join(ROOT, rel)
        if not os.path.exists(p):
            continue
        t = open(p, encoding="utf-8", newline="").read()
        filled = _sub_markers(t, block)
        if filled is None:
            ok = False
            stale.append(f"{rel}:markers-absent")
        elif filled != t:
            ok = False
            stale.append(rel)
            if not check:
                open(p, "w", encoding="utf-8", newline="").write(filled)
    return ok, stale


def main():
    check = "--check" in sys.argv or "--quick" in sys.argv
    ok, stale = run(check)
    if check:
        print(f"doc_counts check: all_ok={ok}" + (f" · stale={stale}" if stale else ""))
        return 0 if ok else 1
    print(f"doc_counts: COUNT-ONTOLOGY.json + {DOC_TARGETS} markers" +
          (f" · updated={stale}" if stale else " · no change"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
